# -*- coding: utf-8 -*-
"""eleicao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18meBA9fC9KWm1Nk4x74uwKP-N1qa-cj2
"""

import numpy as np

candidato_X = 0
candidato_Y = 0
candidato_Z = 0
brancos = 0
nulos = 0

print("======== PROGRAMA DE VOTAÇÃO ========\n\n")
print("Para votar no Candidato X, digite 889")
print("Para votar no Candidato Z, digite 847")
print("Para votar no Candidato Y, digite 515")
print("Para votar em branco, digite 0")
print("Para votar nulo, digite um número fora dos citados anteriormente\n\n")

while True:
  #try:
  voto = int(input("Digite o seu voto:\n"))

  #except:
  if (voto == 889):
    while True:
      candidato_X = candidato_X + 1
      print("\nVoto para o Candidato X registrado.\n")
      break
  
  elif (voto == 847):
    while True:
      candidato_Y = candidato_Y + 1
      print("\nVoto para o Candidato Y registrado.\n")
      break
  
  elif voto == 515:
    while True:
      candidato_Z = candidato_Z + 1
      print("\nVoto para o Candidato Z registrado.\n")
      break

  elif (voto == 0):
    while True:
      brancos = brancos + 1
      print("\nVoto em branco registrado.\n")
      break
  
  else:
    while True:
      nulos = nulos + 1
      print("\nVoto nulo registrado.\n")
      break
  
  while True:
    continuar = str(input("Deseja continuar a votação?\nDigite SIM ou NÃO (isto irá finalizar a votação).\n"))

    if (continuar == "NÃO") or (continuar == "NAO") or (continuar == "não") or (continuar == "nao") or (continuar == "n"):
      if (candidato_X > candidato_Y) and (candidato_X > candidato_Z):
        print("\nO vencedor foi o Candidato X, com um total de: ", candidato_X, "voto(s)")
      
      elif (candidato_Y > candidato_X) and (candidato_Y > candidato_X):
        print("\nO vencedor foi o Candidato Y, com um total de: ", candidato_X, "voto(s)")

      elif (candidato_Z > candidato_X) and (candidato_Z > candidato_Y):
        print("\nO vencedor foi o Candidato Z, com um total de: ", candidato_X, "voto(s)")

      elif (candidato_X == candidato_Y):
        print("\nHouve um empate entre os Candidatos X e Y, com um total de: ", candidato_X, "voto(s)")

      elif (candidato_X == candidato_Z):
        print("\nHouve um empate entre os Candidatos X e Z, com um total de: ", candidato_X, "voto(s)")

      elif (candidato_Y == candidato_Z):
        print("\nHouve um empate entre os Candidatos Y e Z, com um total de: ", candidato_Y, "voto(s)")
      
      elif (candidato_X == candidato_Y == candidato_Z):
        print("\nHouve um empate entre os três Candidatos, com um total de: ", candidato_X, "voto(s)")
      
      print("O número do votos para o Candidato X foi: ", candidato_X)
      print("O número de votos para o Candidato Y foi: ", candidato_Y)
      print("O número de votos para o Candidato Z foi: ", candidato_Z)
      print("O número de votos em branco foi: ", brancos)
      print("O número de votos nulos foi: ", nulos)
      print("O total de votos foi: ", candidato_X + candidato_Y + candidato_Z + brancos + nulos)
      break

    elif (continuar == "SIM") or (continuar == "sim") or (continuar == "ss") or (continuar == "s") or (continuar == "S"):
      break

    else:
      print("Comando inválido. Por favor, siga as instruções mostradas acima.")
      continue

  if continuar == "NÃO": #or (continuar == "NAO") or (continuar == "não") or (continuar == "nao") or (continuar == "n"):
    break